image: maven:latest
cache:
  paths:
    - target/

build:
  stage: build
  script:
    - mvn compile
test:
  stage: test
  script:
    - mvn test

package:
  stage: package
  script:
    - mvn package

deploy:
  stage: deploy
  script:
    - scripts/deploy.sh