# Travis CI Java documentation can be found in:
# https://docs.travis-ci.com/user/languages/java/

# This enables the 'defaults' to test java applications:
language: java

services:
 - docker

# We can specify a list of JDKs to be used for testing
# A list of available JDKs in Trusty can be seed in:
# https://docs.travis-ci.com/user/reference/trusty/#jvm-clojure-groovy-java-scala-images
jdk:
 - oraclejdk11

# Each job in Travis CI has several steps:
# https://docs.travis-ci.com/user/job-lifecycle/
# The 'language: java' directive sets up sane defaults to test common java applications
# We use the defaults for installing dependencies, compiling and testing maven applications
# In our case it will be 'mvn install' followed by 'mvn test'
script:
 - mvn package
 - docker build -t "$DOCKER_USERNAME"/spring_find_weak_server:0.2    .
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker push "$DOCKER_USERNAME"/spring_find_weak_server:0.2


